FROM eclipse-temurin:21-jdk AS build

WORKDIR /app

COPY . .
RUN ./mvnw package -DskipTests

FROM eclipse-temurin:21-jre

WORKDIR /app

COPY --from=build /app/target/agenda-api-0.1.0.jar app.jar

EXPOSE 8080

CMD ["java", "-jar", "app.jar"]
